import java.io.*;

/**
 * Write a program that prints out the the pattern generated by such a scenario 
 * given the values of 'A'/'B' and 'N' which are read from an input text file. 
 * The input text file contains three space delimited numbers i.e. A, B, N. 
 * The program should then print out the final series of numbers using 'F' for 
 * fizz, 'B' for 'buzz' and 'FB' for fizz buzz.
 * 
 * @author Xiaomin Wei
 *
 */
public class FizzBuzz {

	public static void printMsg(int[] input) {
		// check if input is valid
		if (input.length != 3) {
			System.err.println("Invalid length");
			return;
		}
		
		int divFizz = input[0];		// Fizz's divider
		int divBuzz = input[1];		// Buzz's divider
		int length  = input[2];		// total length
		
		StringBuilder str = new StringBuilder();
		
		for (Integer i = 1; i <= length; i++) {
			if (i % (divFizz * divBuzz) == 0)
				str.append("FB ");
			else if (i % divFizz == 0)
				str.append("F ");
			else if (i % divBuzz == 0)
				str.append("B ");
			else {
				str.append(i.toString());
				str.append(" ");
			}
		}
		
		System.out.println(str.toString());
	}
	
	public static void main(String[] args) {
		File file = new File(args[0]);
		try {
			BufferedReader in 
				= new BufferedReader(new FileReader(file));
			
			String line;
			while ((line = in.readLine()) != null) {
				String[] lineArray = line.split("\\s+");
				if (lineArray.length > 0) {
					int[] input = new int[3];
					input[0] = Integer.parseInt(lineArray[0]);
					input[1] = Integer.parseInt(lineArray[1]);
					input[2] = Integer.parseInt(lineArray[2]);
					
					printMsg(input);
				}
			}
			
			in.close();
		} catch (IOException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
		
		
		//int[] input = {2, 7, 15};
		//printMsg(input);
	}

}
